apiVersion: v1
kind: Service
metadata:
  name: ensek-api
  labels:
    app: ensek
    tier: api
spec:
  ports:
  - port: 80
  selector:
    app: ensek
    tier: api
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ensek-api
  labels:
    app: ensek
    tier: api
spec:
  selector:
    matchLabels:
      app: ensek
      tier: api
  template:
    metadata:
      labels:
        app: ensek
        tier: api
    spec:
      containers:
      - name: ensek-api
        image: docker.pkg.github.com/richardthombs/ensek-test/ensek-api:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 80
      imagePullSecrets:
        - name: github
