apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ensek-ingress
  labels:
    app: ensek
    tier: ingress
  annotations:
    kubernetes.io/ingress.class: "nginx"
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
    nginx.ingress.kubernetes.io/from-to-www-redirect: "true"
spec:
  tls:
  - hosts:
    - ensek.gearstone.uk
    secretName: ensek-tls
  rules:
  - host: ensek.app
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: ensek-website
            port:
              number: 80
      - path: /api
        pathType: Prefix
        backend:
          service:
            name: ensek-api
            port:
              number: 80
