apiVersion: v1
kind: Service
metadata:
  name: ensek-website
  labels:
    app: ensek
    tier: website
spec:
  ports:
  - port: 80
  selector:
    app: ensek
    tier: website
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ensek-website
  labels:
    app: ensek
    tier: website
spec:
  selector:
    matchLabels:
      app: ensek
      tier: website
  template:
    metadata:
      labels:
        app: ensek
        tier: website
    spec:
      containers:
      - name: ensek-website
        image: docker.pkg.github.com/richardthombs/ensek-test/ensek-website:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 80
      imagePullSecrets:
        - name: github
